[package]
name = "swap_crate"
version = "0.1.0"
edition = "2021"
authors = ["Mishal Turkane mishalturkane@gmail.com"]
description = "A simple swap function crate"
license = "MIT"
repository = "https://github.com/mishalturkane/swap_crate"

[lib]
name = "swap_crate"
path = "src/lib.rs"
